FROM {{ namespace }}/{{ image_prefix }}base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block kolla_toolbox_header %}{% endblock %}

{% set virtualenv_path='/opt/ansible' %}
{% set os_client_config= virtualenv_path + '/lib/python2.7/site-packages/os_client_config/defaults.json' %}

{% import "macros.j2" as macros with context %}

{{ macros.configure_user(name='ansible') }}

{% if base_distro in ['centos', 'oraclelinux', 'rhel', 'openeuler'] %}
    {% set kolla_toolbox_packages = [
        'gcc',
        'gdisk',
        'git',
        'jq',
        'libffi-devel',
        'libxml2-devel',
        'libxslt-devel',
        'make',
        'openssh-clients',
        'openssl-devel',
        'python2-devel'
     ] %}

     # On x86-64 packages from external repos are used. lowercase names goes
     # conflicts and build fails. Other architectures use standard CentOS
     # packages.
     {% if base_arch == 'x86_64' %}
       {% set kolla_toolbox_packages = kolla_toolbox_packages + [
            'MariaDB-client',
            'MariaDB-devel',
            'MariaDB-shared'
       ] %}
     {% else %}
       {% set kolla_toolbox_packages = kolla_toolbox_packages + [
            'mariadb',
            'mariadb-devel'
       ] %}
     {% endif %}
     
     {% if base_arch == 'sw_64' %}
       {% set kolla_toolbox_packages = kolla_toolbox_packages + [
            'python2-PyMySQL',
            'python2-mysqlclient',
            'python2-pynacl'
       ] %}
     {% endif %}

{% elif base_distro in ['debian', 'ubuntu'] %}
    {% set kolla_toolbox_packages = [
        'build-essential',
        'ca-certificates',
        'crudini',
        'gdisk',
        'git',
        'jq',
        'libffi-dev',
        'libssl-dev',
        'libxslt1-dev',
        'mariadb-client',
        'python-dev'
     ] %}

    {% if base_arch == 'aarch64' and base_distro == 'ubuntu' %}
         {% set kolla_toolbox_packages = kolla_toolbox_packages + [
             'libmysqlclient-dev'
         ] %}
    {% else %}
         {% set kolla_toolbox_packages = kolla_toolbox_packages + [
             'libmariadbclient-dev'
         ] %}
    {% endif %}
    # Debian/stretch ships libmysqlclient.so in separate package
    {% if base_distro == 'debian' %}
        {% set kolla_toolbox_packages = kolla_toolbox_packages + [
            'libmariadbclient-dev-compat'
        ] %}

        {% set os_client_config='/usr/local/lib/python2.7/dist-packages/os_client_config/defaults.json' %}
    {% endif %}

{% endif %}
{{ macros.install_packages(kolla_toolbox_packages | customizable("packages")) }}

{% block kolla_toolbox_source_install_python_pip %}
{% if base_arch == 'sw_64' %}
RUN pip config set global.index-url https://pypi.tuna.tsinghua.edu.cn/simple && \
    pip config set install.trusted-host pypi.tuna.tsinghua.edu.cn
{% else %}
RUN curl https://bootstrap.pypa.io/get-pip.py -o get-pip.py \
    && python get-pip.py \
    && rm get-pip.py
{% endif %}
{% endblock %}

{% set kolla_toolbox_pip_virtualenv_packages = [
        'virtualenv'
    ] %}

RUN {{ macros.install_pip(kolla_toolbox_pip_virtualenv_packages|customizable("pip_packages"), constraints=false) }} \
    && virtualenv --system-site-packages {{ virtualenv_path }}

ENV PATH {{ virtualenv_path }}/bin:$PATH

{% set kolla_toolbox_pip_packages = [
        'ansible==2.2.0.0',
        '"cmd2<0.9.0"',
        'crudini',
        'os-client-config==1.28.0',
        '"openstacksdk<0.18"',
        'pbr==2.0.0',
        'pymongo',
        'python-openstackclient==3.12.0',
        'pytz',
        'pyudev',
        'shade==1.16.0',
        'keystoneauth1==3.1.1',
        'python-ironicclient==1.17.2'
    ] %}

RUN {{ macros.install_pip(kolla_toolbox_pip_packages | customizable("pip_packages"), constraints=false) }} \
    && mkdir -p /etc/ansible /usr/share/ansible \
    && echo 'localhost ansible_connection=local ansible_python_interpreter={{ virtualenv_path }}/bin/python' > /etc/ansible/hosts \
    && sed -i 's|  "identity_api_version": "2.0",|  "identity_api_version": "3",|' {{ os_client_config }}


{% if base_arch == 'sw_64' and base_distro == 'openeuler' %}
{% set kolla_toolbox_pip_packages = [
    'rfc3986==1.2.0',
    'kombu==4.6.6',
    'oslo.middleware==3.31.0',
    'oslo.utils==3.37.0',
    'oslo.log==3.36.0',
    'oslo.context==2.19.2',
    'shade==1.16.0',
    'python-ironicclient==1.17.2',
    'six==1.11.0',
    'openstacksdk==0.9.17',
    'osc_lib==1.7.1'
] %}

RUN {{ macros.install_pip(kolla_toolbox_pip_packages | customizable("pip_packages"), constraints=false) }}
COPY mysql_user.py /opt/ansible/lib/python2.7/site-packages/ansible/modules/core/database/mysql
{% endif %}


ENV ANSIBLE_LIBRARY /usr/share/ansible:$ANSIBLE_LIBRARY

COPY find_disks.py kolla_keystone_service.py kolla_keystone_user.py kolla_sanity.py /usr/share/ansible/
COPY ansible.cfg /var/lib/ansible/.ansible.cfg

COPY ansible_sudoers /etc/sudoers.d/kolla_ansible_sudoers
RUN chmod 440 /etc/sudoers.d/kolla_ansible_sudoers

{% block kolla_toolbox_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER ansible
