FROM {{ namespace }}/{{ image_prefix }}nova-base:{{ tag }}
LABEL maintainer="{{ maintainer }}" name="{{ image_name }}" build-date="{{ build_date }}"

{% block nova_api_header %}{% endblock %}

{% import "macros.j2" as macros with context %}

{% if install_type == 'binary' %}
    {% if base_distro in ['centos', 'oraclelinux', 'rhel'] %}

        {% set nova_api_packages = [
            'httpd',
            'mod_ssl',
            'mod_wsgi',
            'openstack-nova-api'
        ] %}
{{ macros.install_packages(nova_api_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf

    {% elif base_distro in ['debian', 'ubuntu'] %}

        {% set nova_api_packages = [
            'apache2',
            'libapache2-mod-wsgi',
            'nova-api',
            'python-memcache'
        ] %}

{{ macros.install_packages(nova_api_packages | customizable("packages")) }}
RUN echo > /etc/apache2/ports.conf
    {% endif %}

{% elif install_type == 'source' %}

    {% if base_distro in ['centos', 'oraclelinux', 'rhel', 'openeuler'] %}

        {% set nova_api_packages = [
            'httpd',
            'mod_ssl',
            'python2-mod_wsgi'
        ] %}
{{ macros.install_packages(nova_api_packages | customizable("packages")) }}
RUN sed -i -r 's,^(Listen 80),#\1,' /etc/httpd/conf/httpd.conf \
    && sed -i -r 's,^(Listen 443),#\1,' /etc/httpd/conf.d/ssl.conf \
    && /usr/libexec/httpd-ssl-gencerts

    {% elif base_distro in ['debian', 'ubuntu'] %}

        {% set nova_api_packages = [
            'apache2',
            'libapache2-mod-wsgi'
        ] %}

{{ macros.install_packages(nova_api_packages | customizable("packages")) }}
RUN echo > /etc/apache2/ports.conf

    {% endif %}

{% endif %}

{% if base_arch == 'sw_64' and base_distro == 'openeuler' %}
{% set nova_api_pip_packages = [
    'rfc3986==1.2.0',
    'kombu==4.6.6',
    'oslo.middleware==3.31.0',
    'oslo.utils==3.37.0',
    'oslo.log==3.36.0',
    'oslo.context==2.19.2',
    'shade==1.16.0',
    'python-ironicclient==1.17.2',
    'six==1.11.0'
] %}

RUN {{ macros.install_pip(nova_api_pip_packages | customizable("pip_packages"), constraints=false) }}

{% endif %}

COPY extend_start.sh /usr/local/bin/kolla_nova_extend_start
RUN chmod 755 /usr/local/bin/kolla_nova_extend_start

{% block nova_api_footer %}{% endblock %}
{% block footer %}{% endblock %}

USER nova
